export const players = [
  { ranking: 1, name: "Jannik Sinner", country: "ITA", points: 11830 },
  { ranking: 2, name: "Alexander Zverev", country: "GER", points: 8135 },
  { ranking: 3, name: "Carlos Alcaraz", country: "ESP", points: 7555 },
  { ranking: 4, name: "Taylor Fritz", country: "USA", points: 5100 },
  { ranking: 5, name: "Daniil Medvedev", country: "RUS", points: 5030 },
  { ranking: 6, name: "Casper Ruud", country: "NOR", points: 4255 },
  { ranking: 7, name: "Novak Djokovic", country: "SRB", points: 3900 },
  { ranking: 8, name: "Alex de Minaur", country: "AUS", points: 3745 },
  { ranking: 9, name: "Andrey Rublev", country: "RUS", points: 3520 },
  { ranking: 10, name: "Grigor Dimitrov", country: "BUL", points: 3340 },
  { ranking: 11, name: "Stefanos Tsitsipas", country: "GRE", points: 3165 },
  { ranking: 12, name: "Tommy Paul", country: "USA", points: 3145 },
  { ranking: 13, name: "Holger Rune", country: "DEN", points: 3025 },
  { ranking: 14, name: "Lorenzo Musetti", country: "ITA", points: 2600 },
  { ranking: 15, name: "Jack Draper", country: "GBR", points: 2525 },
  { ranking: 16, name: "Ugo Humbert", country: "FRA", points: 2420 },
  { ranking: 17, name: "Frances Tiafoe", country: "USA", points: 2355 },
  { ranking: 18, name: "Hubert Hurkacz", country: "POL", points: 2310 },
  { ranking: 19, name: "Karen Khachanov", country: "RUS", points: 2245 },
  { ranking: 20, name: "Arthur Fils", country: "FRA", points: 2180 },
  { ranking: 21, name: "Sebastian Korda", country: "USA", points: 2095 },
  { ranking: 22, name: "Ben Shelton", country: "USA", points: 2070 },
  { ranking: 23, name: "Alejandro Tabilo", country: "CHI", points: 2025 },
  { ranking: 24, name: "Felix Auger-Aliassime", country: "CAN", points: 1995 },
  { ranking: 25, name: "Jiri Lehecka", country: "CZE", points: 1940 },
  { ranking: 26, name: "Francisco Cerundolo", country: "ARG", points: 1895 },
  { ranking: 27, name: "Nicolas Jarry", country: "CHI", points: 1860 },
  { ranking: 28, name: "Alexei Popyrin", country: "AUS", points: 1825 },
  { ranking: 29, name: "Sebastian Baez", country: "ARG", points: 1790 },
  { ranking: 30, name: "Giovanni Mpetshi Perricard", country: "FRA", points: 1755 },
  { ranking: 31, name: "Tomas Machac", country: "CZE", points: 1720 },
  { ranking: 32, name: "Jordan Thompson", country: "AUS", points: 1685 },
  { ranking: 33, name: "Matteo Arnaldi", country: "ITA", points: 1650 },
  { ranking: 34, name: "Flavio Cobolli", country: "ITA", points: 1615 },
  { ranking: 35, name: "Brandon Nakashima", country: "USA", points: 1580 },
  { ranking: 36, name: "Mariano Navone", country: "ARG", points: 1545 },
  { ranking: 37, name: "Tallon Griekspoor", country: "NED", points: 1510 },
  { ranking: 38, name: "Lorenzo Sonego", country: "ITA", points: 1475 },
  { ranking: 39, name: "Matteo Berrettini", country: "ITA", points: 1440 },
  { ranking: 40, name: "Luciano Darderi", country: "ITA", points: 1405 },
  { ranking: 41, name: "Jan-Lennard Struff", country: "GER", points: 1370 },
  { ranking: 42, name: "Adrian Mannarino", country: "FRA", points: 1335 },
  { ranking: 43, name: "Alexander Bublik", country: "KAZ", points: 1300 },
  { ranking: 44, name: "Cameron Norrie", country: "GBR", points: 1265 },
  { ranking: 45, name: "Marcos Giron", country: "USA", points: 1230 },
  { ranking: 46, name: "Facundo Diaz Acosta", country: "ARG", points: 1195 },
  { ranking: 47, name: "Roberto Bautista Agut", country: "ESP", points: 1160 },
  { ranking: 48, name: "Pavel Kotov", country: "RUS", points: 1125 },
  { ranking: 49, name: "Jakub Mensik", country: "CZE", points: 1090 },
  { ranking: 50, name: "Yoshihito Nishioka", country: "JPN", points: 1055 },
  { ranking: 51, name: "Zhizhen Zhang", country: "CHN", points: 1025 },
  { ranking: 52, name: "Tomas Martin Etcheverry", country: "ARG", points: 1000 },
  { ranking: 53, name: "Alejandro Davidovich Fokina", country: "ESP", points: 975 },
  { ranking: 54, name: "Pedro Martinez", country: "ESP", points: 950 },
  { ranking: 55, name: "Botic van de Zandschulp", country: "NED", points: 925 },
  { ranking: 56, name: "Alexander Shevchenko", country: "KAZ", points: 900 },
  { ranking: 57, name: "Gael Monfils", country: "FRA", points: 880 },
  { ranking: 58, name: "Roberto Carballes Baena", country: "ESP", points: 860 },
  { ranking: 59, name: "Yunchaokete Bu", country: "CHN", points: 840 },
  { ranking: 60, name: "Rinky Hijikata", country: "AUS", points: 820 },
  { ranking: 61, name: "Daniel Altmaier", country: "GER", points: 800 },
  { ranking: 62, name: "Hugo Gaston", country: "FRA", points: 780 },
  { ranking: 63, name: "Maximilian Marterer", country: "GER", points: 760 },
  { ranking: 64, name: "Camilo Ugo Carabelli", country: "ARG", points: 740 },
  { ranking: 65, name: "Nuno Borges", country: "POR", points: 720 },
  { ranking: 66, name: "Miomir Kecmanovic", country: "SRB", points: 700 },
  { ranking: 67, name: "Hugo Humbert", country: "FRA", points: 685 },
  { ranking: 68, name: "Christopher Eubanks", country: "USA", points: 670 },
  { ranking: 69, name: "Thiago Seyboth Wild", country: "BRA", points: 655 },
  { ranking: 70, name: "Daniel Evans", country: "GBR", points: 640 },
  { ranking: 71, name: "Dusan Lajovic", country: "SRB", points: 625 },
  { ranking: 72, name: "Damir Dzumhur", country: "BIH", points: 610 },
  { ranking: 73, name: "Thanasi Kokkinakis", country: "AUS", points: 595 },
  { ranking: 74, name: "Fabian Marozsan", country: "HUN", points: 580 },
  { ranking: 75, name: "Adam Walton", country: "AUS", points: 565 },
  { ranking: 76, name: "Jaume Munar", country: "ESP", points: 550 },
  { ranking: 77, name: "David Goffin", country: "BEL", points: 535 },
  { ranking: 78, name: "Alexandre Muller", country: "FRA", points: 520 },
  { ranking: 79, name: "Zizou Bergs", country: "BEL", points: 505 },
  { ranking: 80, name: "Constant Lestienne", country: "FRA", points: 490 },
  { ranking: 81, name: "Aleksandar Vukic", country: "AUS", points: 480 },
  { ranking: 82, name: "Luca Nardi", country: "ITA", points: 470 },
  { ranking: 83, name: "Sumit Nagal", country: "IND", points: 460 },
  { ranking: 84, name: "Dominik Koepfer", country: "GER", points: 450 },
  { ranking: 85, name: "James Duckworth", country: "AUS", points: 440 },
  { ranking: 86, name: "Laslo Djere", country: "SRB", points: 430 },
  { ranking: 87, name: "Albert Ramos-Vinolas", country: "ESP", points: 420 },
  { ranking: 88, name: "Federico Coria", country: "ARG", points: 410 },
  { ranking: 89, name: "Billy Harris", country: "GBR", points: 400 },
  { ranking: 90, name: "Gregoire Barrere", country: "FRA", points: 390 },
  { ranking: 91, name: "Corentin Moutet", country: "FRA", points: 380 },
  { ranking: 92, name: "Shang Juncheng", country: "CHN", points: 370 },
  { ranking: 93, name: "Roman Safiullin", country: "RUS", points: 360 },
  { ranking: 94, name: "Lloyd Harris", country: "RSA", points: 350 },
  { ranking: 95, name: "Harold Mayot", country: "FRA", points: 340 },
  { ranking: 96, name: "Quentin Halys", country: "FRA", points: 330 },
  { ranking: 97, name: "Francesco Passaro", country: "ITA", points: 320 },
  { ranking: 98, name: "Thiago Monteiro", country: "BRA", points: 310 },
  { ranking: 99, name: "Richard Gasquet", country: "FRA", points: 300 },
  { ranking: 100, name: "Taro Daniel", country: "JPN", points: 295 },
  { ranking: 101, name: "Dennis Novak", country: "AUT", points: 290 },
  { ranking: 102, name: "Elias Ymer", country: "SWE", points: 285 },
  { ranking: 103, name: "Arthur Cazaux", country: "FRA", points: 280 },
  { ranking: 104, name: "Yosuke Watanuki", country: "JPN", points: 275 },
  { ranking: 105, name: "Radu Albot", country: "MDA", points: 270 },
  { ranking: 106, name: "Valentin Vacherot", country: "MON", points: 265 },
  { ranking: 107, name: "Felipe Meligeni Alves", country: "BRA", points: 260 },
  { ranking: 108, name: "Maxime Cressy", country: "USA", points: 255 },
  { ranking: 109, name: "Cristian Garin", country: "CHI", points: 250 },
  { ranking: 110, name: "Emilio Nava", country: "USA", points: 245 },
  { ranking: 111, name: "Learner Tien", country: "USA", points: 240 },
  { ranking: 112, name: "Alex Michelsen", country: "USA", points: 235 },
  { ranking: 113, name: "Jurij Rodionov", country: "AUT", points: 230 },
  { ranking: 114, name: "Lukas Klein", country: "SVK", points: 225 },
  { ranking: 115, name: "Bernabe Zapata Miralles", country: "ESP", points: 220 },
  { ranking: 116, name: "Daniel Masur", country: "GER", points: 215 },
  { ranking: 117, name: "Dimitri Baskov", country: "BLR", points: 210 },
  { ranking: 118, name: "Henrique Rocha", country: "POR", points: 205 },
  { ranking: 119, name: "Henri Squire", country: "GER", points: 200 },
  { ranking: 120, name: "Otto Virtanen", country: "FIN", points: 195 },
  { ranking: 121, name: "Andrea Vavassori", country: "ITA", points: 190 },
  { ranking: 122, name: "Tseng Chun-hsin", country: "TPE", points: 185 },
  { ranking: 123, name: "Geoffrey Blancaneaux", country: "FRA", points: 180 },
  { ranking: 124, name: "Dominic Stricker", country: "SUI", points: 175 },
  { ranking: 125, name: "Yasutaka Uchiyama", country: "JPN", points: 170 },
  { ranking: 126, name: "Nicolas Moreno de Alboran", country: "USA", points: 165 },
  { ranking: 127, name: "Mikhail Kukushkin", country: "KAZ", points: 160 },
  { ranking: 128, name: "Antoine Escoffier", country: "FRA", points: 155 },
  { ranking: 129, name: "Benjamin Bonzi", country: "FRA", points: 150 },
  { ranking: 130, name: "Timofey Skatov", country: "KAZ", points: 148 },
  { ranking: 131, name: "Coleman Wong", country: "HKG", points: 146 },
  { ranking: 132, name: "Tristan Schoolkate", country: "AUS", points: 144 },
  { ranking: 133, name: "Vilius Gaubas", country: "LTU", points: 142 },
  { ranking: 134, name: "Alibek Kachmazov", country: "RUS", points: 140 },
  { ranking: 135, name: "Juan Manuel Cerundolo", country: "ARG", points: 138 },
  { ranking: 136, name: "Carlos Taberner", country: "ESP", points: 136 },
  { ranking: 137, name: "Mattia Bellucci", country: "ITA", points: 134 },
  { ranking: 138, name: "Gabriel Diallo", country: "CAN", points: 132 },
  { ranking: 139, name: "Lucas Pouille", country: "FRA", points: 130 },
  { ranking: 140, name: "Dominic Thiem", country: "AUT", points: 128 },
  { ranking: 141, name: "Alexander Ritschard", country: "SUI", points: 126 },
  { ranking: 142, name: "Stefano Napolitano", country: "ITA", points: 124 },
  { ranking: 143, name: "Titouan Droguet", country: "FRA", points: 122 },
  { ranking: 144, name: "Terence Atmane", country: "FRA", points: 120 },
  { ranking: 145, name: "Stefano Travaglia", country: "ITA", points: 118 },
  { ranking: 146, name: "Manuel Guinard", country: "FRA", points: 116 },
  { ranking: 147, name: "Aziz Dougaz", country: "TUN", points: 114 },
  { ranking: 148, name: "Tristan Boyer", country: "USA", points: 112 },
  { ranking: 149, name: "Giovanni Fonio", country: "ITA", points: 110 },
  { ranking: 150, name: "Lukas Neumayer", country: "AUT", points: 108 },
  { ranking: 151, name: "Santiago Rodriguez Taverna", country: "ARG", points: 106 },
  { ranking: 152, name: "Duje Ajdukovic", country: "CRO", points: 104 },
  { ranking: 153, name: "Marc-Andrea Huesler", country: "SUI", points: 102 },
  { ranking: 154, name: "Gastao Elias", country: "POR", points: 100 },
  { ranking: 155, name: "Andrea Pellegrino", country: "ITA", points: 98 },
  { ranking: 156, name: "Franco Agamenone", country: "ARG", points: 96 },
  { ranking: 157, name: "Federico Gaio", country: "ITA", points: 94 },
  { ranking: 158, name: "Nicolas Mejia", country: "COL", points: 92 },
  { ranking: 159, name: "Sho Shimabukuro", country: "JPN", points: 90 },
  { ranking: 160, name: "Joao Fonseca", country: "BRA", points: 88 },
  { ranking: 161, name: "Murkel Dellien", country: "BOL", points: 86 },
  { ranking: 162, name: "Andrew Harris", country: "AUS", points: 84 },
  { ranking: 163, name: "Jozef Kovalik", country: "SVK", points: 82 },
  { ranking: 164, name: "Liam Broady", country: "GBR", points: 80 },
  { ranking: 165, name: "Kimmer Coppejans", country: "BEL", points: 78 },
  { ranking: 166, name: "Matheus Pucinelli", country: "BRA", points: 76 },
  { ranking: 167, name: "Diego Hidalgo", country: "ECU", points: 74 },
  { ranking: 168, name: "Borna Gojo", country: "CRO", points: 72 },
  { ranking: 169, name: "Lucas Miedler", country: "AUT", points: 70 },
  { ranking: 170, name: "Alexis Galarneau", country: "CAN", points: 68 },
  { ranking: 171, name: "Matteo Gigante", country: "ITA", points: 66 },
  { ranking: 172, name: "Juan Pablo Varillas", country: "PER", points: 64 },
  { ranking: 173, name: "Clement Chidekh", country: "FRA", points: 62 },
  { ranking: 174, name: "Raul Brancaccio", country: "ITA", points: 60 },
  { ranking: 175, name: "Frederico Ferreira Silva", country: "POR", points: 58 },
  { ranking: 176, name: "Marco Trungelliti", country: "ARG", points: 56 },
  { ranking: 177, name: "Filip Cristian Jianu", country: "ROU", points: 54 },
  { ranking: 178, name: "Emilio Gomez", country: "ECU", points: 52 },
  { ranking: 179, name: "Peter Gojowczyk", country: "GER", points: 50 },
  { ranking: 180, name: "Zsombor Piros", country: "HUN", points: 48 },
  { ranking: 181, name: "Filip Misolic", country: "AUT", points: 46 },
  { ranking: 182, name: "Andrea Collarini", country: "ARG", points: 44 },
  { ranking: 183, name: "Pol Martin Tiffon", country: "ESP", points: 42 },
  { ranking: 184, name: "Dalibor Svrcina", country: "CZE", points: 40 },
  { ranking: 185, name: "Jaime Faria", country: "POR", points: 38 },
  { ranking: 186, name: "Martin Landaluce", country: "ESP", points: 36 },
  { ranking: 187, name: "Edas Butvilas", country: "LTU", points: 34 },
  { ranking: 188, name: "Nicolas Alvarez Varona", country: "ESP", points: 32 },
  { ranking: 189, name: "Jesper de Jong", country: "NED", points: 30 },
  { ranking: 190, name: "Santiago FA Taverna", country: "ARG", points: 28 },
  { ranking: 191, name: "Ryan Peniston", country: "GBR", points: 26 },
  { ranking: 192, name: "Lukas Rosol", country: "CZE", points: 24 },
  { ranking: 193, name: "Maxime Janvier", country: "FRA", points: 22 },
  { ranking: 194, name: "Facundo Bagnis", country: "ARG", points: 20 },
  { ranking: 195, name: "Filip Horansky", country: "SVK", points: 18 },
  { ranking: 196, name: "Enzo Couacaud", country: "FRA", points: 16 },
  { ranking: 197, name: "Matteo Martineau", country: "FRA", points: 14 },
  { ranking: 198, name: "Franco Roncadelli", country: "URU", points: 12 },
  { ranking: 199, name: "Juan Bautista Torres", country: "ARG", points: 10 },
  { ranking: 200, name: "Genaro Alberto Olivieri", country: "ARG", points: 8 },
];